version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/ustraa
hooks:
  ApplicationStop:
    - location: codeDeployScripts/stop_node_application.sh
      runas: ubuntu
  AfterInstall:
    - location: codeDeployScripts/start_node_application.sh
      runas: ubuntu
permissions:
    - object: /var/www/html/ustraa
      pattern: "**"
      owner: ubuntu
      mode: 777
      type:
        - file
        
    - object: /var/www/html/ustraa
      pattern: "**"
      owner: ubuntu
      mode: 777
      type:
        - directory
