version: 0.0
os: linux
files:
  - source: /
    destination: /mnt/hu_ustraa
hooks:
  ApplicationStop:
    - location: codeDeployScripts/stop_node_application.sh
      runas: ubuntu
  AfterInstall:
    - location: codeDeployScripts/start_node_application.sh
      runas: ubuntu
permissions:
    - object: /mnt/hu_ustraa
      pattern: "**"
      owner: ubuntu
      group: ubuntu
      mode: 644
      type:
        - file
        
    - object: /mnt/hu_ustraa
      pattern: "**"
      owner: ubuntu
      group: ubuntu
      mode: 755
      type:
        - directory
